language: node_js
node_js:
  - "8.9"
  - "8.0"
branches:
  only:
    - master
    - develop

install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - ./cc-test-reporter upload-coverage -i ./coverage/lcov.info
before_deploy:
  - npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
