language: node_js
node_js:
  - "8.9"
  - "8.0"
branches:
  only:
    - master
    - develop

before_deploy:
  - npm run build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
