name: Create Page

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSIRIS_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Deploy
        run: |
          yarn install --frozen-lockfile
          yarn deploy
